; PlatformIO Project Configuration File for health-kicks-esp32-s3
; Microcontrôleur : ESP32-S3-N16R8 (16MB Flash Octal / 8MB PSRAM Octal)

[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

monitor_speed = 115200
upload_speed = 921600
monitor_dtr = 0
monitor_rts = 0

; Flash 16MB Quad SPI + PSRAM Octal 8MB
board_build.arduino.memory_type = qio_opi
board_build.flash_mode = qio
board_upload.flash_size = 16MB
board_build.partitions = default_8MB.csv

build_flags = 
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue
    -DCONFIG_SPIRAM_MODE_OCT=1
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1

lib_deps = 
    h2zero/NimBLE-Arduino @ ^1.4.2

