#!/usr/bin/env python3
"""Model Transpilation Tool for HealthKicks ESP32-S3 Firmware.

Converts a trained scikit-learn activity classification model (.joblib) into
a self-contained, high-performance pure C header file for embedded execution.
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import Any

try:
    import joblib
    import m2cgen as m2c
    import numpy as np
except ImportError:
    print("Error: Missing required Python packages (joblib, m2cgen, numpy).")
    print("Install with: pip install joblib m2cgen numpy scikit-learn")
    sys.exit(1)


CANONICAL_FEATURES = [
    "acc_mag_max",
    "acc_mag_min",
    "acc_mag_mean",
    "acc_mag_std",
    "acc_mag_peak_to_peak",
    "gyro_mag_max",
    "gyro_mag_mean",
    "gyro_mag_std",
    "ax_std",
    "ay_std",
    "az_std",
    "gx_std",
    "gy_std",
    "gz_std",
    "acc_energy",
    "gyro_energy",
]

STATE_CODE_MAP = {
    "idle": "0x00",
    "walk": "0x01",
    "run": "0x02",
    "stairs": "0x03",
    "fall_forward": "0x10",
    "fall_backward": "0x11",
    "fall_lateral": "0x12",
    "stumble_recover": "0x1E",
    "fall_generic": "0x1F",
}


def load_model_and_metadata(model_path: Path) -> tuple[Any, list[str], list[str], float, dict[str, Any]]:
    """Loads model artifact and extracts estimator, feature names, classes, and scaler."""
    if not model_path.exists():
        raise FileNotFoundError(f"Model file not found: {model_path}")

    data = joblib.load(model_path)
    metadata: dict[str, Any] = {}

    if isinstance(data, dict):
        estimator = data.get("estimator", data)
        feature_names = data.get("feature_names", CANONICAL_FEATURES)
        classes = data.get("classes", [])
        window_size_sec = float(data.get("window_size_sec", 2.0))
        metadata = data
    else:
        estimator = data
        feature_names = CANONICAL_FEATURES
        window_size_sec = 2.0
        classes = []

    # Handle pipeline if present
    scaler = None
    if hasattr(estimator, "steps"):
        for step_name, step_obj in estimator.steps:
            if hasattr(step_obj, "mean_") and hasattr(step_obj, "scale_"):
                scaler = step_obj
            elif hasattr(step_obj, "predict"):
                estimator = step_obj

    if not classes and hasattr(estimator, "classes_"):
        classes = [str(c) for c in estimator.classes_]

    if not classes:
        classes = ["fall_forward", "idle", "stairs", "stumble_recover", "walk"]

    metadata["scaler"] = scaler
    return estimator, feature_names, classes, window_size_sec, metadata


def generate_c_header(
    estimator: Any,
    feature_names: list[str],
    classes: list[str],
    window_size_sec: float,
    metadata: dict[str, Any],
) -> str:
    """Transpiles the classifier and formats the generated C header."""
    import re
    c_raw_code = m2c.export_to_c(estimator, function_name="raw_predict_activity")

    # Ensure all helper functions are static/inline for header-only inclusion
    c_raw_code = c_raw_code.replace("void add_vectors(", "inline void add_vectors(")
    c_raw_code = c_raw_code.replace("void mul_vector_number(", "inline void mul_vector_number(")
    c_raw_code = c_raw_code.replace("void raw_predict_activity(", "inline void raw_predict_activity(")

    # Fix C++ compatibility for C99 compound literal memcpy (e.g. taking address of temporary array in G++)
    c_raw_code = re.sub(
        r"memcpy\((\w+),\s*\(double\s*\[\s*\]\)\{([^}]+)\},\s*[^;]+\);",
        r"{ const double _tmp[] = {\2}; memcpy(\1, _tmp, sizeof(_tmp)); }",
        c_raw_code,
    )

    # Convert local intermediate variables to static storage to eliminate stack usage on embedded FreeRTOS tasks
    c_raw_code = re.sub(
        r"(\n\s*)double\s+(var\d+(\[\d+\])?);",
        r"\1static double \2;",
        c_raw_code,
    )

    feature_count = len(feature_names)
    class_count = len(classes)
    window_samples = int(round(window_size_sec * 19)) # 19 Hz nominal rate = 38 samples

    class_names_c = ", ".join([f'"{c}"' for c in classes])
    state_codes_c = ", ".join([STATE_CODE_MAP.get(c, "0x00") for c in classes])
    fall_flags_c = ", ".join(["true" if c.startswith("fall") else "false" for c in classes])
    feature_names_c = ", ".join([f'"{f}"' for f in feature_names])

    scaler = metadata.get("scaler")
    has_scaler = scaler is not None and hasattr(scaler, "mean_") and hasattr(scaler, "scale_")

    scaler_mean_str = ""
    scaler_scale_str = ""
    if has_scaler:
        scaler_mean_str = ", ".join([f"{float(m):.8f}" for m in scaler.mean_])
        scaler_scale_str = ", ".join([f"{float(s):.8f}" for s in scaler.scale_])

    header = f"""// ============================================================================
// AUTO-GENERATED EDGE CLASSIFICATION MODEL (DO NOT EDIT MANUALLY)
// Generated by tools/export_model_to_c.py
// ============================================================================
#pragma once

#include <stdint.h>
#include <stdbool.h>
#include <string.h>
#include <math.h>

#define MODEL_FEATURE_COUNT     {feature_count}
#define MODEL_CLASS_COUNT       {class_count}
#define MODEL_WINDOW_SIZE_SEC   {window_size_sec:.1f}f
#define MODEL_SAMPLE_RATE_HZ    19
#define MODEL_WINDOW_SAMPLES    {window_samples}

// Feature identifiers
static const char* const MODEL_FEATURE_NAMES[MODEL_FEATURE_COUNT] = {{
    {feature_names_c}
}};

// Class labels table
static const char* const MODEL_CLASS_NAMES[MODEL_CLASS_COUNT] = {{
    {class_names_c}
}};

// BLE State Code mapping table
static const uint8_t MODEL_CLASS_STATE_CODES[MODEL_CLASS_COUNT] = {{
    {state_codes_c}
}};
#define MODEL_CLASS_TO_GATT_STATE MODEL_CLASS_STATE_CODES

// Critical Fall classification mask
static const bool MODEL_IS_FALL_CLASS[MODEL_CLASS_COUNT] = {{
    {fall_flags_c}
}};
#define MODEL_CLASS_IS_FALL MODEL_IS_FALL_CLASS

#define MODEL_HAS_SCALER        {"1" if has_scaler else "0"}
"""

    if has_scaler:
        header += f"""
static const double MODEL_SCALER_MEAN[MODEL_FEATURE_COUNT] = {{
    {scaler_mean_str}
}};

static const double MODEL_SCALER_SCALE[MODEL_FEATURE_COUNT] = {{
    {scaler_scale_str}
}};
"""

    header += f"""
// ----------------------------------------------------------------------------
// Core transpiled decision logic (m2cgen)
// ----------------------------------------------------------------------------
namespace generated_model {{
{c_raw_code}
}} // namespace generated_model

/**
 * @brief Evaluates the feature vector and computes class scores.
 * @param features Input feature vector of size MODEL_FEATURE_COUNT.
 * @param scores Output score array of size MODEL_CLASS_COUNT.
 */
inline void evaluate_model(const double* features, double* scores) {{
#if MODEL_HAS_SCALER
    double normalized[MODEL_FEATURE_COUNT];
    for (int i = 0; i < MODEL_FEATURE_COUNT; ++i) {{
        normalized[i] = (features[i] - MODEL_SCALER_MEAN[i]) / MODEL_SCALER_SCALE[i];
    }}
    generated_model::raw_predict_activity(normalized, scores);
#else
    // Const-cast safe copy for transpiled function signature
    double input_copy[MODEL_FEATURE_COUNT];
    memcpy(input_copy, features, sizeof(input_copy));
    generated_model::raw_predict_activity(input_copy, scores);
#endif
}}
"""
    return header


def main() -> None:
    parser = argparse.ArgumentParser(description="Export scikit-learn model to C header for ESP32-S3")
    parser.add_argument(
        "--model",
        type=Path,
        default=Path("scripts/models/activity_classifier.joblib"),
        help="Path to trained .joblib model file",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("include/activity_model_generated.h"),
        help="Path for generated C header output",
    )

    args = parser.parse_args()

    # Search fallback paths if not found directly
    model_path = args.model
    if not model_path.exists():
        candidates = [
            Path("../health-kicks/scripts/models/activity_classifier.joblib"),
            Path("../health-kicks-edge-script/models/activity_classifier.joblib"),
            Path("models/activity_classifier.joblib"),
        ]
        for c in candidates:
            if c.exists():
                model_path = c
                break

    print(f"Loading model from: {model_path}")
    estimator, feature_names, classes, window_size_sec, metadata = load_model_and_metadata(model_path)
    print(f"Model estimator: {type(estimator).__name__}")
    print(f"Classes ({len(classes)}): {classes}")
    print(f"Features ({len(feature_names)}): {feature_names}")

    c_header = generate_c_header(estimator, feature_names, classes, window_size_sec, metadata)

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(c_header, encoding="utf-8")
    print(f"Successfully generated C model header: {args.output} ({len(c_header)} bytes)")


if __name__ == "__main__":
    main()
